#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php'))
{
	require __DIR__.'/vendor/autoload.php';
}
else
{
	require __DIR__.'/../../autoload.php';
}

function base_path()
{
	if (func_num_args() == 0) {
		return __DIR__;
	}
	else {
		return __DIR__ . '/' . implode('/', func_get_args());
	}
}

function atshell_path()
{
	if (func_num_args() == 0) {
		if (isset($_SERVER['HOME']))
		{
			return $_SERVER['HOME'].'/.atsh';
		}
		else
		{
			return $_SERVER['HOMEDRIVE'].$_SERVER['HOMEPATH'].DIRECTORY_SEPARATOR.'.atsh';
		}
	}
	else {
		return atshell_path() . '/' . implode('/', func_get_args());;
	}
}

$app = new Symfony\Component\Console\Application('Atshell', '0.0.1');

$app->add(new Jumilla\Atshell\InitCommand);
$app->add(new Jumilla\Atshell\UpCommand);

$app->run();
